version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistem_lpk
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

  webserver:
    image: nginx:alpine
    container_name: lpk_webserver
    restart: unless-stopped
    ports:
      - "83:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      
  mysql:
      image: mysql:8.0
      container_name: lpk
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_INITDB_SKIP_TZINFO: 1
      volumes:
        - dbdata:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 10s
        retries: 10
      ports:
        - "3309:3306"
volumes:
  dbdata:
